// packages/react/src/base-dropdown.tsx
import * as menu from '@zag-js/menu';
import { normalizeProps, useMachine } from '@zag-js/react';
import React, { HTMLAttributes, useId } from 'react';

import { BaseButton } from './base-button';
import { WalletUiSize } from './types/wallet-ui-size';

export interface BaseDropdownItem {
    closeMenu?: boolean;
    disabled?: boolean;
    handler: () => void;
    label: string;
    leftSection?: React.ReactNode;
    rightSection?: React.ReactNode;
    value: string;
}

export interface BaseDropdownProps {
    buttonLabel: React.ReactNode;
    buttonLeftSection?: React.ReactNode;
    buttonSize?: WalletUiSize;
    items: BaseDropdownItem[];
    showIndicator?: boolean;
}

export function BaseDropdown({
    buttonLabel,
    buttonLeftSection,
    buttonSize = 'md',
    showIndicator,
    items,
}: BaseDropdownProps) {
    const service = useMachine(menu.machine, { id: useId() });
    const api = menu.connect(service, normalizeProps);

    const trigger = (
        <BaseButton
            {...api.getTriggerProps()}
            className={`wallet-ui-base-dropdown-trigger`}
            data-part="trigger"
            leftSection={buttonLeftSection}
            rightSection={
                showIndicator ? (
                    <span className="wallet-actions">
                        <span {...api.getIndicatorProps()} className="indicator">
                            <BaseDropdownChevronDown size={12} />
                        </span>
                    </span>
                ) : null
            }
            size={buttonSize}
        >
            {buttonLabel}
        </BaseButton>
    );

    return (
        <div className="wallet-ui-base-dropdown">
            {trigger}
            <div {...api.getPositionerProps()} className="wallet-positioner">
                <ul {...api.getContentProps()} className="wallet-ui-base-dropdown-list" data-part="content">
                    {items.map(item => (
                        <li
                            key={item.value}
                            {...api.getItemProps({ value: item.value })}
                            className="wallet-ui-base-dropdown-item"
                            data-part="item"
                            onClick={() => {
                                if (item.disabled) {
                                    return;
                                }
                                item.handler();
                                if (item.closeMenu !== false) {
                                    service.send({ type: 'CLOSE' });
                                }
                            }}
                        >
                            {item.leftSection ? (
                                <span className="wallet-ui-base-dropdown-item-left-section">{item.leftSection}</span>
                            ) : null}
                            {item.label}
                            {item.rightSection ? (
                                <span className="wallet-ui-base-dropdown-item-right-section">{item.rightSection}</span>
                            ) : null}
                        </li>
                    ))}
                </ul>
            </div>
        </div>
    );
}

export function BaseDropdownChevronDown(props: HTMLAttributes<SVGElement> & { size?: number }) {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width={props.size ?? 24}
            height={props.size ?? 24}
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            {...props}
        >
            <path d="m6 9 6 6 6-6" />
        </svg>
    );
}

// packages/svelte/src/lib/components/base-dropdown.svelte
<script lang="ts">
import * as menu from "@zag-js/menu"
import { portal, useMachine, normalizeProps } from "@zag-js/svelte"
import type { WalletUiSize } from '../wallet-state.svelte.js';
import type { UiWallet } from 'wallet-standard-svelte';
import type { Snippet } from 'svelte';
import WalletUiIcon from '../WalletUiIcon.svelte';

interface BaseDropdownItem {
    closeMenu?: boolean;
    disabled?: boolean;
    handler: () => Promise<void>;
    label: string;
    leftSection?: Snippet;
    rightSection?: Snippet;
    type: string;
    value: string;
    wallet?: UiWallet;
    showCheckmark?: boolean;
}

interface Props {
    buttonProps?: Record<string, string | number | boolean>;
    items: BaseDropdownItem[];
    showIndicator?: boolean;
    size?: WalletUiSize;
    children?: Snippet;
}

let { buttonProps = {}, items, showIndicator = true, size = 'md', children }: Props = $props();

const uid = $props.id();

const service = useMachine(menu.machine, { id: uid })
const api = $derived(menu.connect(service, normalizeProps))

function handleItemClick(item: BaseDropdownItem) {
    if (item.disabled) return;
    
    item.handler().then(() => {
        if (item.closeMenu !== false) {
            service.send({ type: 'CLOSE' });
        }
    });
}
</script>

<div data-wu="base-dropdown">
    <button {...api.getTriggerProps()} {...buttonProps} data-wu="base-button" class="{size} {buttonProps?.class ?? ''}">
        {@render children?.()}
        {#if showIndicator}
            <span {...api.getIndicatorProps()}>
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="m6 9 6 6 6-6" />
                </svg>
            </span>
        {/if}
    </button>
    
    <div use:portal {...api.getPositionerProps()} data-wu="base-dropdown-wrapper">
        <div {...api.getContentProps()} data-wu="base-dropdown-list" data-part="content">
            {#each items as item}
                <button 
                    {...api.getItemProps({ value: item.value })}
                    data-wu="base-dropdown-item" 
                    class={size}
                    data-part="item"
                    onclick={() => handleItemClick(item)}
                    disabled={item.disabled}
                >
                    {#if item.wallet}
                        <span data-wu="base-dropdown-item-left-section">
                            <WalletUiIcon wallet={item.wallet} {size} />
                        </span>
                    {/if}
                    {#if item.leftSection}
                        <span data-wu="base-dropdown-item-left-section">{@render item.leftSection()}</span>
                    {/if}
                    {item.label}
                    {#if item.rightSection}
                        <span data-wu="base-dropdown-item-right-section">{@render item.rightSection()}</span>
                    {:else if item.showCheckmark}
                        <span data-wu="base-dropdown-item-right-section">✓</span>
                    {/if}
                </button>
            {/each}
        </div>
    </div>
</div>
