// packages/react/src/base-button.tsx
import React from 'react';

import { WalletUiButton } from './types/wallet-ui-button';
import { WalletUiSize } from './types/wallet-ui-size';

export interface BaseButtonProps extends Omit<WalletUiButton, 'children'> {
    label: React.ReactNode;
    leftSection?: React.ReactNode;
    onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void;
    rightSection?: React.ReactNode;
    size?: WalletUiSize;
}

export function BaseButton({ className, label, leftSection, onClick, rightSection, size, ...props }: BaseButtonProps) {
    return (
        <button data-ui="base-button" className={`${size ?? 'md'} ${className ?? ''}`} onClick={onClick} {...props}>
            {leftSection ? <span data-ui="base-button-left-section">{leftSection}</span> : null}
            {label}
            {rightSection ? <span data-ui="base-button-right-section">{rightSection}</span> : null}
        </button>
    );
}

// packages/svelte/src/lib/components/base-button.svelte
<script lang="ts">
import type { WalletUiSize } from '../wallet-state.svelte.js';
import type { Snippet } from 'svelte';

interface Props {
    size?: WalletUiSize;
    leftSection?: Snippet;
    rightSection?: Snippet;
    label?: string;
    disabled?: boolean;
    onclick?: (event: MouseEvent) => void;
    children?: Snippet;
    class?: string;
    [key: string]: string | number | boolean | Snippet | ((event: MouseEvent) => void) | undefined;
}

let { 
    size = 'md', 
    leftSection, 
    rightSection, 
    label, 
    disabled = false, 
    onclick,
    children,
    class: className = '',
    ...restProps 
}: Props = $props();
</script>

<button 
    data-wu="base-button" 
    class="{size} {className ?? ''}"
    {disabled}
    {onclick}
    {...restProps}
>
    {#if leftSection}
        <span data-wu="base-button-left-section">{@render leftSection()}</span>
    {/if}
    {#if label}
        {label}
    {:else if children}
        {@render children()}
    {/if}
    {#if rightSection}
        <span data-wu="base-button-right-section">{@render rightSection()}</span>
    {/if}
</button>
