// packages/svelte/src/lib/WalletUiLabel.svelte
<script lang="ts">
import type { UiWallet } from 'wallet-standard-svelte';
import type { WalletUiSize } from './wallet-state.svelte.js';

interface Props {
    wallet?: UiWallet;
    size?: WalletUiSize;
    class?: string;
}

let { wallet, size = 'md', class: className }: Props = $props();
</script>

{#if wallet}
    <span 
        class="{size} {className ?? ''}"
        data-wu="wallet-ui-label"
    >
        {wallet.name}
    </span>
{/if}

// packages/react/src/wallet-ui-label.tsx
import { UiWallet } from '@wallet-standard/react';
import React from 'react';

import { WalletUiSize } from './types/wallet-ui-size';

export interface WalletUiLabelProps
    extends React.DetailedHTMLProps<React.HTMLAttributes<HTMLSpanElement>, HTMLSpanElement> {
    size?: WalletUiSize;
    wallet?: Pick<UiWallet, 'name'>;
}

export function WalletUiLabel({ className, size, wallet, ...props }: WalletUiLabelProps) {
    if (!wallet) {
        return null;
    }

    return (
        <span data-wu="wallet-ui-label" className={`${size ?? 'md'} ${className ?? ''}`} {...props}>
            {wallet.name}
        </span>
    );
}
