// packages/svelte/src/lib/WalletUiList.svelte
<script lang="ts">
import type { UiWallet, UiWalletAccount } from 'wallet-standard-svelte';
import type { WalletUiSize } from './wallet-state.svelte.js';
import WalletUiListButton from './WalletUiListButton.svelte';

interface Props {
    wallets: UiWallet[];
    size?: WalletUiSize;
    class?: string;
    select?: (account: UiWalletAccount) => Promise<void>;
}

let { wallets, size = 'md', class: className, select }: Props = $props();
</script>

<div 
    data-wu="wallet-ui-list"
    class="{size} {className ?? ''}"
>
    {#each wallets as wallet (wallet.name)}
        <WalletUiListButton {wallet} {size} {select} />
    {/each}
</div>

// packages/react/src/wallet-ui-list.tsx
import { UiWallet, UiWalletAccount } from '@wallet-standard/react';
import React from 'react';

import { WalletUiDiv } from './types/wallet-ui-div';
import { WalletUiSize } from './types/wallet-ui-size';
import { WalletUiListButton } from './wallet-ui-list-button';

export interface WalletUiListProps extends WalletUiDiv {
    select?: (account: UiWalletAccount) => Promise<void>;
    size?: WalletUiSize;
    wallets: UiWallet[];
}

export function WalletUiList({ className, select, size = 'md', wallets, ...props }: WalletUiListProps) {
    return (
        <div data-wu="wallet-ui-list" className={`${size} ${className ?? ''}`} {...props}>
            {wallets.map(wallet => (
                <WalletUiListButton key={wallet.name} select={select} size={size} wallet={wallet} />
            ))}
        </div>
    );
}
