// packages/react/src/wallet-ui-cluster-dropdown.tsx
import React from 'react';

import { BaseDropdown, BaseDropdownProps } from './base-dropdown';
import { WalletUiSize } from './types/wallet-ui-size';
import { useBaseDropdown } from './use-base-dropdown';
import { useWalletUiCluster } from './use-wallet-ui-cluster';

export interface WalletUiClusterDropdownProps
    extends Omit<BaseDropdownProps, 'buttonProps' | 'dropdown' | 'items' | 'label'> {
    buttonProps?: Partial<BaseDropdownProps['buttonProps']>;
    size?: WalletUiSize;
}

export function WalletUiClusterDropdown({ buttonProps, size = 'md', ...props }: WalletUiClusterDropdownProps) {
    const dropdown = useBaseDropdown();
    const { cluster, clusters, setCluster } = useWalletUiCluster();
    return (
        <BaseDropdown
            buttonProps={{ ...buttonProps, label: cluster.label, size: size }}
            items={clusters.map(cluster => ({
                handler: () => setCluster(cluster.id),
                label: cluster.label,
                value: cluster.id,
            }))}
            dropdown={dropdown}
            {...props}
        />
    );
}

// packages/svelte/src/lib/WalletUiClusterDropdown.svelte
<script lang="ts">
import BaseDropdown from './components/base-dropdown.svelte';
import { useWalletUi } from './use-wallet-ui.js';
import type { WalletUiSize } from './wallet-state.svelte.js';
import type { SolanaCluster } from '@wallet-ui/core';

interface Props {
    size?: WalletUiSize;
    class?: string;
    clusters: SolanaCluster[];
}

let { size, class: className, clusters }: Props = $props();

const wallet = useWalletUi();

// Create dropdown items from clusters
const items = $derived(clusters.map(cluster => ({
    label: cluster.label,
    value: cluster.id,
    type: 'cluster',
    showCheckmark: wallet.cluster?.id === cluster.id,
    disabled: false,
    handler: async () => {
        wallet.setCluster(cluster);
    }
})));
</script>

<div data-wu="wallet-ui-cluster-dropdown">
    <BaseDropdown {items} {size} buttonProps={{ class: className || '' }}>
        {wallet.cluster?.label || 'Select Cluster'}
    </BaseDropdown>
</div>
